### ISSUE TITLE
add new language

### ISSUE THREAD

**Issue by dohoeppner** [dohoeppner/capstone-project#14]
## Value Proposition
As a user I want to add a new language so that I can learn more than one language within the same app.

## Description
<img width="241" alt="Screenshot 2022-04-04 at 11 09 26" src="https://user-images.githubusercontent.com/98758161/161512008-9a23c8b8-28fc-4e78-85a3-ec493b533244.png">
(PlusButton to create a new language leads bei clicking on the button to the AddLanguageForm/Overlay)

## Acceptance Criteria

- [x] By clicking the PlusButton a form opens in which the user can enter a new language and the (official) language code.
- [x] By clicking the AddLanguageButton the language is added to the list of languages (HomePage).
- [x] If the language was already created an error message will be thrown when filling the code-input-field and the AddButton will be disabled.

##Tasks

- [x] Create a PlusButton on HomePage(was already already done in a previous user story)
- [x] Create a Form-Overlay
- [x] Create a form with two input-fields (add new language / add language code)
- [x] Create an AddLanguageButton
- [x] Add error-message when language/language-code already exists in list 
- [x] Style the Form
