### ISSUE TITLE
delete language

### ISSUE THREAD

**Issue by dohoeppner** [dohoeppner/capstone-project#15]
## Value Proposition
As a user I want to delete a created language so that I am able to delete languages I added.

## Description
On the Hompage a DeleteLanguageButton should be added so that the User is able to edit languages which are not used any longer or were accidentally added to the list.

## Acceptance Criteria

- [x] A DeleteButton is added to each LanguageButton in the list of languages.
- [x] By clicking the DeleteButton the language will be completely deleted.

## Tasks

- [x] Create a DeleteButton
- [x] Add event handler on DeleteButton
