### ISSUE TITLE
card interface

### ISSUE THREAD

**Issue by dohoeppner** [dohoeppner/capstone-project#2]
## Value Preposition
As a User I need to see one card/word to be able to repeat/memorize the word.

## Description
<img width="269" alt="Screenshot 2022-03-28 at 08 35 49" src="https://user-images.githubusercontent.com/98758161/160339933-10a9088e-a117-4a40-b46f-6b5d186c578e.png">

## Acceptance Criteria

- [x] See the card interface with a word.

## Tasks

- [x] Create card component / design
- [x]  Create all the UI element of the card
