### ISSUE TITLE
search result

### ISSUE THREAD

**Issue by dohoeppner** [dohoeppner/capstone-project#20]
## Value Proposition
As a user I need to see my search result so that I can handle the word that was found (edit, delete, put back into collection).

## Description
<img width="243" alt="Screenshot 2022-04-11 at 11 47 14" src="https://user-images.githubusercontent.com/98758161/162712703-42c68fb9-c061-40ad-9a27-8960b1759bba.png">

## Acceptance Criteria

- [x] Word the user chose in the SearchPage appears in the form (foreign language / translation)
- [x] Edit-, Back-into-collection- and Delete-Button
- [x] Functionality of the buttons

## Tasks

- [x] UI (form, buttons)
- [x] event handler on buttons
- [x] Closing button to leave this page
