### ISSUE TITLE
Create profile(Page)

### ISSUE THREAD

**Issue by dohoeppner** [dohoeppner/capstone-project#22]
## Value Proposition
As a user I want to be able to access to a profile page so that I get an overview over my language-settings.

## Description
<img width="233" alt="Screenshot 2022-04-18 at 15 31 25" src="https://user-images.githubusercontent.com/98758161/163815619-fa39e04c-7ec7-4dde-80aa-23ec71a27186.png">

## Acceptance Criteria

- [x] UI Profile Page for one "example user"
- [x] Profile Picture
- [x] Name of the user
- [x] Learning language overview of the user

## Tasks

- [x] UI Profile Page
- [x] Frame for Profile picture
- [x] Display of username
- [x] Import LanguageList component
