### ISSUE TITLE
Implementation of choose-language functionality

### ISSUE THREAD

**Issue by dohoeppner** [dohoeppner/capstone-project#24]
## Value Proposition
As a User I want to select one of my languages so that all my activities (learn, search, create) are connected to the chosen language.

## Description
By clicking on one of my languages (HomePage or ProfilePage) the user chooses its current learning language (including the features "create a new word" and "serach for a word").

## Acceptance Criteria

- [x] By clicking on one of the language buttons the user can choose a current learning language.
- [x] The chosen language has to have a different style than the inactive languages.

## Tasks

- [x] Change "active"-style
- [x] Add onClick event to choose this language
- [x] Add React Context
