### ISSUE TITLE
Throw set off random cards

### ISSUE THREAD

**Issue by dohoeppner** [dohoeppner/capstone-project#28]
## Value Proposition
As a user I want to get a set of randomly chosen cards so that I can repeat my words in a special repetition algorithm.

## Description
When the user starts to practice he/she will receive a set of 5 randomly chosen cards (of the current learning language).

## Acceptance Criteria

- [x] When starting to practice the user receives a set of 5 randomly chosen cards (of the current learning language) - learnPage
- [x] These cards shouldn't be archived yet.

## Tasks

- [x] Implement random functionality on "Practice now"-button (HomePage) and "ContinueButton" (LearnPage)
