### ISSUE TITLE
Add algorithm functionality to Failure- and CheckButton (learnPage)

### ISSUE THREAD

**Issue by dohoeppner** [dohoeppner/capstone-project#29]
## Value Proposition
As a user I want to do the repetition of the words in a special timeframe so that I remember the words more and more easily.

## Description
<img width="231" alt="Screenshot 2022-04-21 at 10 38 15" src="https://user-images.githubusercontent.com/98758161/164415366-2af29a2c-48ad-4037-b0e3-084e30e9b332.png">
(By clicking on the red button the word stays in the "learning loop", by clicking the green button the word will be archived. This is a simple algorithm for the start. The final repetition value should be more complex/detailed.)

## Acceptance Criteria

- [x] Clicking the read button: the card/word will be back in the loop and stays available for practice.
- [x] Clicking the green button: the card/word will be archived and is no longer part of the practicing loop.

## Tasks

- [x] Plug functionality on red button, precise the onClick event.
- [x] Plug functionality on green button, precise the onClick event ("archived").
