### ISSUE TITLE
toggle card

### ISSUE THREAD

**Issue by dohoeppner** [dohoeppner/capstone-project#3]
## Value Preposition
As a User I need to turn the card to be able to check if I memorized the word correctly.

## Description
<img width="277" alt="Screenshot 2022-03-25 at 16 35 16" src="https://user-images.githubusercontent.com/98758161/160340168-bb7230b9-429a-4b4f-bd84-0d070321ac82.png">

Toggle-Button has to be filled with action.

## Acceptance Criteria

- [x] The card has to be toggleable.

## Tasks

- [x] create a toggle-button
- [x] implement the event handler (toggle on click)
