### ISSUE TITLE
check answer

### ISSUE THREAD

**Issue by dohoeppner** [dohoeppner/capstone-project#4]
## Value preposition
As a user I want to choose if I was right or wrong so that I can repeat the word/expression later again.

## Description
<img width="274" alt="Screenshot 2022-03-28 at 08 39 38" src="https://user-images.githubusercontent.com/98758161/160340445-458db44d-c8e7-469a-a0a2-af0d7cf9d7b6.png">

## Acceptance Criteria

In addition to the toggle-button the interface as to show a...
- [x] Red button for "I was wrong"
- [x] Green button for "I was right"

## Tasks

- [x] create a red button
- [x] create a green button
- [x] implement event handler on both buttons
