### ISSUE TITLE
switch to new card

### ISSUE THREAD

**Issue by dohoeppner** [dohoeppner/capstone-project#5]
## Value Preposition
As a user I want to get a new card so that I can continue my repetition.

## Description
<img width="664" alt="Screenshot 2022-03-28 at 08 40 47" src="https://user-images.githubusercontent.com/98758161/160340631-d37a94f7-00fb-4a47-90cc-a66086861637.png">

((back to previous screen))

## Acceptance Criteria

- [x] By clicking on the "Next card"-button the screen has to change and show a new word/card

## Tasks

- [x] create button component
- [x] add "Next Card"-button to the page
- [x] add event handler on click go back to previous page and show a new word
