### ISSUE TITLE
create new vocabulary card

### ISSUE THREAD

**Issue by dohoeppner** [dohoeppner/capstone-project#6]
## Value Preposition
As a user I want to create a new card (word plus translation) so that I can enhance my collection of words.

## Description
<img width="282" alt="Screenshot 2022-03-25 at 15 35 37" src="https://user-images.githubusercontent.com/98758161/160141704-725bcceb-67f4-42f4-963b-4dd0bbb0aac1.png">
(form to create a new voc-card)

## Acceptance Criteria

- [x] fillable form
- [x] textfield for word (foreign language)
- [x] textfield for translation (prob. mother tongue)

## Tasks

- [x] create a form with two textfields on CreatePage
- [x] Textfield 1 for "Foreign language" (placeholder: Add a new word)
- [x] Textfield 2 for "Translation" (placeholder: Add translation)
- [x] Create CreateCardButton
