### ISSUE TITLE
add new word to collection

### ISSUE THREAD

**Issue by dohoeppner** [dohoeppner/capstone-project#7]
## Value Preposition
As a user I want to add the currently created card to my collection so that it will be part of my repetition circle.

## Description
<img width="271" alt="Screenshot 2022-03-25 at 15 21 53" src="https://user-images.githubusercontent.com/98758161/160141501-78c16dbd-2b90-4c22-9fa8-8a4b8b31a7dd.png">
(create button)

## Acceptance Criteria

- [x] Working "Create"-button

## Tasks

- [x] Add "create button"
- [x] Add event handler on click add new word to collection/array/database
- [x] Empty form after clicking the create button.
