### ISSUE TITLE
avoiding doublets

### ISSUE THREAD

**Issue by dohoeppner** [dohoeppner/capstone-project#8]
## Value Preposition
As a user I want to get a hint in case the new word/expression is already added to my collection so that I don't create doublets.

## Description
When the user wants to add a word to the collection that already exists he/she will get a notification and the word is not added.

## Acceptance criteria

- [x] When the user wants to add a word to the collection that already exists he/she will get a notification and the word is not added.

- [x] The user can edit the translation and submit the editing by clicking on the submit button.

## Tasks

- [x] Implement editing option
- [x] add event on submit/create button
